placeholders:
    view_content_data_additional_information:
        items:
            oro_bts_user_issues: ~

items:
    oro_bts_user_issues:
        template: OroBundleBtsBundle:User:issues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)

