Oro\Bundle\BtsBundle\Entity\Issue:
    alias: oro_btsbundle_issue
    label: oro.bts.issue.entity_plural_label
    title_fields: [code, summary]
    search_template: OroBundleBtsBundle:Search:result.html.twig
    route:
        name: oro_bts_issue_view
        parameters:
            id: id
    fields:
        -
            name: code
            target_type: text
        -
            name: summary
            target_type: text
            target_fields: [summary, description]
        -
            name: type
            relation_type: many-to-one
            relation_fields:
                -
                    name: label
                    target_type: text
                    target_fields: [label, all_data]
                -
                    name: id
                    target_type: integer
                    target_fields: [type]
        -
            name: resolution
            relation_type: many-to-one
            relation_fields:
                -
                    name: label
                    target_type: text
                    target_fields: [label, all_data]
                -
                    name: id
                    target_type: integer
                    target_fields: [resolution]
        -
            name: priority
            relation_type: many-to-one
            relation_fields:
                -
                    name: label
                    target_type: text
                    target_fields: [label, all_data]
                -
                    name: id
                    target_type: integer
                    target_fields: [priority]
        -
            name: reporter
            relation_type: many-to-one
            relation_fields:
                -
                    name: username
                    target_type: text
                    target_fields: [username, all_data]
                -
                    name: id
                    target_type: integer
                    target_fields: [reporter]
        -
            name: owner
            relation_type: many-to-one
            relation_fields:
                -
                    name: username
                    target_type: text
                    target_fields: [username, all_data]
                -
                    name: id
                    target_type: integer
                    target_fields: [owner]
