parameters:
    oro_bts.issue.entity.class:               Oro\Bundle\BtsBundle\Entity\Issue
    oro_bts.issue.form.type.class:            Oro\Bundle\BtsBundle\Form\Type\IssueType
    oro_bts.issue.form.handler.class:         Oro\Bundle\BtsBundle\Form\Handler\IssueHandler
    oro_bts.issue.listener.class:         Oro\Bundle\BtsBundle\EventListener\IssueListener

    oro_bts.issue.priority.entity.class:      Oro\Bundle\BtsBundle\Entity\IssuePriority
    oro_bts.issue.resolution.entity.class:    Oro\Bundle\BtsBundle\Entity\IssueResolution
    oro_bts.issue.type.entity.class:          Oro\Bundle\BtsBundle\Entity\IssueType

    oro_bts.issue.form.type.api.class:        Oro\Bundle\BtsBundle\Form\Type\Api\IssueApiType
    oro_bts.manager.api.class:                Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_bts_soap.handler.delete.class:        Oro\Bundle\BtsBundle\Form\Handler\DeleteIssueHandler

services:
    oro_bts.form.type.issue:
        class: %oro_bts.issue.form.type.class%
        tags:
            - { name: form.type, alias: oro_btsbundle_issue }

    oro_bts.form.issue:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "oro_btsbundle_issue_form"
            - "oro_btsbundle_issue"
            - ~

    oro_bts.form.handler.issue:
        class: %oro_bts.issue.form.handler.class%
        scope: request
        arguments:
            - @oro_bts.form.issue
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    oro_bts.form.type.api.issue:
        class:           %oro_bts.issue.form.type.api.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: issue }

    oro_bts.form.api.issue:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "issue"
            - "issue"
            - null

    oro_bts.form.handler.api.issue:
        class: %oro_bts.issue.form.handler.class%
        scope: request
        arguments:
            - @oro_bts.form.api.issue
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    oro_bts.issue_manager.api:
        class: %oro_bts.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_bts.issue.entity.class%
            - @doctrine.orm.entity_manager

    oro_bts_soap.handler.delete.abstract:
        abstract: true
        calls:
            - [setOwnerDeletionManager, [@oro_organization.owner_deletion_manager]]

    oro_bts_soap.handler.delete:
        class: %oro_bts_soap.handler.delete.class%
        parent: oro_bts_soap.handler.delete.abstract

    oro_bts_issue.listener:
        class: %oro_bts.issue.listener.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }
        arguments: ["@service_container"]